apiVersion: delivery.ocm.software/v1alpha1
kind: FluxDeployer
metadata:
  name: istio-istiod
  namespace: default
spec:
  interval: 10m0s
  sourceRef:
    apiVersion: delivery.ocm.software/v1alpha1
    kind: Resource
    name: istio-istiod
  helmReleaseTemplate:
    interval: 10s
    releaseName: istio-istiod
    targetNamespace: istio-system
    dependsOn:
    - name: istio-base
      namespace: default
    driftDetection:
      mode: disabled
      ignore:
        - paths: [ "/spec/replicas" ]
        - paths: [ "/data" ]
    values:
      meshConfig:
        defaultConfig:
          holdApplicationUntilProxyStarts: true