apiVersion: apis.kcp.io/v1alpha2
kind: APIBinding
metadata:
  name: authorization.platform-mesh.io
spec:
  permissionClaims:
  - resource: logicalclusters
    group: core.kcp.io
    selector:
      matchAll: true
    verbs:
      - '*'
    state: Accepted
  reference:
    export:
      name: authorization.platform-mesh.io
      path: root:platform-mesh-system
