apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: system.platform-mesh.io
spec:
  latestResourceSchemas:
  - v260217-2c67392.identityproviderconfigurations.core.platform-mesh.io
  - v260313-c8b198d.apiexportpolicies.core.platform-mesh.io
  permissionClaims:
    - all: true
      group: tenancy.kcp.io
      identityHash: {{ .apiExportRootTenancyKcpIoIdentityHash }}
      resource: workspaces
    - all: true
      group: tenancy.kcp.io
      identityHash: {{ .apiExportRootTenancyKcpIoIdentityHash }}
      resource: workspacetypes
    - resource: apibindings
      group: apis.kcp.io
      all: true
      identityHash: ""
    - resource: apiexports
      group: apis.kcp.io
      all: true
      identityHash: ""
    - resource: apiresourceschemas
      group: apis.kcp.io
      all: true
      identityHash: ""
    - resource: logicalclusters
      group: core.kcp.io
      all: true
      identityHash: ""
    - resource: secrets
      group: ""
      all: true
      identityHash: ""
status: {}
