apiVersion: ui.platform-mesh.io/v1alpha1
kind: ContentConfiguration
metadata:
  labels:
    ui.platform-mesh.io/entity: core_platform-mesh_io_account
  name: account-namespaces
spec:
  inlineConfiguration:
    content: |-
      {
          "name": "namespaces",
          "creationTimestamp": "2022-05-17T11:37:17Z",
          "luigiConfigFragment": {
              "data": {
                  "nodes": [
                      {
                          "pathSegment": "namespaces",
                          "navigationContext": "namespaces",
                          "label": "Namespaces",
                          "entityType": "main.core_platform-mesh_io_account",
                          "icon": "group-2",
                          "order": 110,
                          "category": {
                              "id": "workspace",
                              "isGroup": true,
                              "label": "Workspace Resources",
                              "order": 500
                          },
                          "loadingIndicator": {
                              "enabled": false
                          },
                          "keepSelectedForChildren": true,
                          "url": "/assets/platform-mesh-portal-ui-wc.js#generic-list-view",
                          "webcomponent": {
                              "selfRegistered": true
                          },
                          "context": {
                              "resourceDefinition": {
                                  "version": "v1",
                                  "entityCollection": "Namespaces",
                                  "entity": "Namespace",
                                  "scope": "Cluster",
                                  "namespace": null,
                                  "ui": {
                                      "listView": {
                                          "fields": [
                                              {
                                                  "label": "Name",
                                                  "property": "metadata.name"
                                              },
                                              {
                                                  "property": "metadata.name",
                                                  "uiSettings": {
                                                      "align": "end",
                                                      "displayAs": "button",
                                                      "columnWidth": "90px",
                                                      "buttonSettings": {
                                                          "icon": "decline",
                                                          "design": "Transparent",
                                                          "action": "delete-resource",
                                                          "tooltip": "Delete"
                                                      }
                                                  },
                                                  "group": {
                                                      "name": "actions",
                                                      "label": "",
                                                      "multiline": false
                                                  }
                                              }
                                          ]
                                      },
                                      "createView": {
                                          "fields": [
                                              {
                                                  "label": "Name",
                                                  "property": "metadata.name",
                                                  "required": true
                                              }
                                          ]
                                      }
                                  }
                              }
                          }
                      }
                  ]
              }
          }
      }
    contentType: json
