apiVersion: delivery.ocm.software/v1alpha1
kind: FluxDeployer
metadata:
  name: observability
  namespace: default
spec:
  interval: 10m0s
  sourceRef:
    apiVersion: delivery.ocm.software/v1alpha1
    kind: Resource
    name: observability
  helmReleaseTemplate:
    interval: 10s
    releaseName: observability
    targetNamespace: openmfp-system
    dependsOn:
      - name: istio-istiod
        namespace: default
    driftDetection:
      mode: enabled
      ignore:
        - paths: [ "/spec/replicas" ]
        - paths: [ "/data" ]
    values:
      istio:
        grafana:
          virtualService:
            hosts: ["grafana.{{ .BASE_DOMAIN }}"]
        tracing:
          enabled: true
      opentelemetry-collector:
        service:
          type: ClusterIP
        ports:
          metrics:
            enabled: true
        image:
          repository: "otel/opentelemetry-collector-k8s"
          tag: 0.123.0