with-expecter: true
packages:
  # internal
  github.com/platform-mesh/platform-mesh-operator/pkg/subroutines:
    config:
      dir: pkg/subroutines/mocks
      outpkg: mocks
    interfaces:
      KcpHelper:
        config:
          mockname: KcpHelper

  # external
  sigs.k8s.io/controller-runtime/pkg/client:
    config:
      dir: pkg/subroutines/mocks
      outpkg: mocks
    interfaces:
      Client:
        config:
          mockname: Client
  sigs.k8s.io/controller-runtime/pkg/manager:
    config:
      dir: pkg/subroutines/mocks
      outpkg: mocks
    interfaces:
      Manager:
        config:
          mockname: Manager