exclude:
  paths:
    - ^pkg/subroutines/mocks # exclude generated mock files
    - api/v1alpha1 # skipping generated files and crd type definitions
    - main\.go$ # skip covering main.go
    - ^cmd # skip covering cmd directory
    - ^pkg/testing # skip covering kcpenvtest
    - ^test/
    - ^setup/
    - .*_testexports.go
    - pkg/subroutines/deployment.go
    - pkg/subroutines/patch_oidc.go
    - internal/controller/realm_controller.go

