# TODO: Check if this file is needed for the cluster creation
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 31000
    hostPort: 8443
    protocol: TCP
    listenAddress: "127.0.0.1"
  - containerPort: 32000
    hostPort: 15021
    protocol: TCP
    listenAddress: "127.0.0.1"
