apiVersion: delivery.ocm.software/v1alpha1
kind: FluxDeployer
metadata:
  name: keycloak
  namespace: default
spec:
  interval: 10m0s
  sourceRef:
    apiVersion: delivery.ocm.software/v1alpha1
    kind: Resource
    name: keycloak
  helmReleaseTemplate:
    interval: 10s
    releaseName: keycloak
    targetNamespace: openmfp-system
    dependsOn:
      - name: istio-istiod
        namespace: default
    driftDetection:
      mode: enabled
      ignore:
        - paths: [ "/spec/replicas" ]
        - paths: [ "/data" ]
    values:
      service:
        name: keycloak
      externalSecrets:
        keycloakAdminRemoteRef: keycloak-admin
        postgresAdminRemoteRef: postgres-admin
      keycloak:
        extraEnvVars:
          - name: JAVA_OPTS_APPEND
            value: |-
              -Djgroups.dns.query=keycloak-headless.openmfp-system.svc.cluster.local
          - name: KC_PROXY_HEADERS
            value: xforwarded
          - name: KC_HOSTNAME_STRICT
            value: "false"
      domain:
        pathPrefix: "/keycloak"
      istio:
        https:
          enabled: true
        virtualservice:
          hosts:
            - {{ .BASE_DOMAIN }}
      crossplane:
        clients:
          openmfp:
            validRedirectUris:
              - "{{ .PROTOCOL }}://{{ .BASE_DOMAIN }}{{ .COLON_PORT }}/callback*"
      keycloakConfig:
        url: http://keycloak.openmfp-system.svc.cluster.local/keycloak
        redirectUrls:
          - "{{ .BASE_DOMAIN }}{{ .COLON_PORT }}/callback*"
        