apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: account-operator.webhooks.core.platform-mesh.io
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: {{ index . "account-operator.webhooks.core.platform-mesh.io.ca-bundle" }}
      url: https://account-operator-webhook.platform-mesh-system.svc.cluster.local:9443/mutate-core-platform-mesh-io-v1alpha1-account
    failurePolicy: Fail
    name: maccount.kb.io
    rules:
      - apiGroups:
          - core.platform-mesh.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
        resources:
          - accounts
    sideEffects: None
    timeoutSeconds: 30
