// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"k8s.io/client-go/rest"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

// NewKcpHelper creates a new instance of KcpHelper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKcpHelper(t interface {
	mock.TestingT
	Cleanup(func())
}) *KcpHelper {
	mock := &KcpHelper{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// KcpHelper is an autogenerated mock type for the KcpHelper type
type KcpHelper struct {
	mock.Mock
}

type KcpHelper_Expecter struct {
	mock *mock.Mock
}

func (_m *KcpHelper) EXPECT() *KcpHelper_Expecter {
	return &KcpHelper_Expecter{mock: &_m.Mock}
}

// NewKcpClient provides a mock function for the type KcpHelper
func (_mock *KcpHelper) NewKcpClient(config *rest.Config, workspacePath string) (client.Client, error) {
	ret := _mock.Called(config, workspacePath)

	if len(ret) == 0 {
		panic("no return value specified for NewKcpClient")
	}

	var r0 client.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*rest.Config, string) (client.Client, error)); ok {
		return returnFunc(config, workspacePath)
	}
	if returnFunc, ok := ret.Get(0).(func(*rest.Config, string) client.Client); ok {
		r0 = returnFunc(config, workspacePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*rest.Config, string) error); ok {
		r1 = returnFunc(config, workspacePath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KcpHelper_NewKcpClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewKcpClient'
type KcpHelper_NewKcpClient_Call struct {
	*mock.Call
}

// NewKcpClient is a helper method to define mock.On call
//   - config *rest.Config
//   - workspacePath string
func (_e *KcpHelper_Expecter) NewKcpClient(config interface{}, workspacePath interface{}) *KcpHelper_NewKcpClient_Call {
	return &KcpHelper_NewKcpClient_Call{Call: _e.mock.On("NewKcpClient", config, workspacePath)}
}

func (_c *KcpHelper_NewKcpClient_Call) Run(run func(config *rest.Config, workspacePath string)) *KcpHelper_NewKcpClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *rest.Config
		if args[0] != nil {
			arg0 = args[0].(*rest.Config)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *KcpHelper_NewKcpClient_Call) Return(client1 client.Client, err error) *KcpHelper_NewKcpClient_Call {
	_c.Call.Return(client1, err)
	return _c
}

func (_c *KcpHelper_NewKcpClient_Call) RunAndReturn(run func(config *rest.Config, workspacePath string) (client.Client, error)) *KcpHelper_NewKcpClient_Call {
	_c.Call.Return(run)
	return _c
}
