# permissions for end users to view openmfps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openmfp-operator
    app.kubernetes.io/managed-by: kustomize
  name: openmfp-viewer-role
rules:
- apiGroups:
  - core.openmfp.org
  resources:
  - openmfps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.openmfp.org
  resources:
  - openmfps/status
  verbs:
  - get
