---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.platform-mesh.io
  resources:
  - platformmeshes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.platform-mesh.io
  resources:
  - platformmeshes/finalizers
  verbs:
  - update
- apiGroups:
  - core.platform-mesh.io
  resources:
  - platformmeshes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - providers.platform-mesh.io
  resources:
  - managedproviders
  - providers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - providers.platform-mesh.io
  resources:
  - managedproviders/finalizers
  - providers/finalizers
  verbs:
  - update
- apiGroups:
  - providers.platform-mesh.io
  resources:
  - managedproviders/status
  - providers/status
  verbs:
  - get
  - patch
  - update
