apiVersion: delivery.ocm.software/v1alpha1
kind: FluxDeployer
metadata:
  name: kcp
  namespace: default
spec:
  interval: 10m0s
  sourceRef:
    apiVersion: delivery.ocm.software/v1alpha1
    kind: Resource
    name: kcp
  helmReleaseTemplate:
    interval: 10s
    releaseName: kcp
    targetNamespace: openmfp-system
    dependsOn:
      - name: istio-istiod
        namespace: default
    driftDetection:
      mode: enabled
      ignore:
        - paths: [ "/spec/replicas" ]
        - paths: [ "/data" ]
    values:
      auth:
        adminCert:
          issuerRef: kcp-front-proxy-client-issuer
      webhook:
        enabled: true
        server: https://iam-authorization-webhook.openmfp-system.svc.cluster.local:9443/authz
        caData: {{ .IAM_WEBHOOK_CA }}
      istio:
        hosts:
         - "kcp.api.{{ .BASE_DOMAIN }}"
        gateway:
          create: false
      kcp:
        externalPort: "{{ .PORT }}"
        externalHostname: "kcp.api.{{ .BASE_DOMAIN }}"
        kcp:
          podAnnotations:
            traffic.sidecar.istio.io/excludeOutboundPorts: "9443"
          authorization:
            webhook:
              secretName: kcp-webhook-secret
        oidc:
          enabled: true
          issuerUrl: https://{{ .BASE_DOMAIN }}{{ .COLON_PORT }}/keycloak/realms/openmfp
          clientId: openmfp
          groupClaim: groups
          usernameClaim: email
        kcpFrontProxy:
          extraDNSNames:
            - kcp-front-proxy.openmfp-system
        certificates:
          dnsNames:
            - kcp.openmfp-system
            - localhost
            - kcp.{{ .BASE_DOMAIN }}