apiVersion: v1
kind: Secret
metadata:
  name: kcp-webhook-secret
  namespace: platform-mesh-system
type: Opaque
stringData:
  kubeconfig: |
    apiVersion: v1
    kind: Config
    clusters:
    - name: webhook
      cluster:
          server: https://rebac-authz-webhook.platform-mesh-system.svc.cluster.local:9443/authz
    current-context: webhook
    contexts:
    - name: webhook
      context:
        cluster: webhook