apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rebac-authz-webhook-cert
  namespace: platform-mesh-system
spec:
  secretName: rebac-authz-webhook-cert
  issuerRef:
    name: rebac-authz-webhook-issuer
  dnsNames:
  - rebac-authz-webhook.platform-mesh-system.svc.cluster.local