{{- if .prometheusOperatorCRDs.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ .prometheusOperatorCRDs.name }}
  namespace: {{ .helmReleaseNamespace }}
  labels:
    core.platform-mesh.io/operator-created: "true"
spec:
{{- if .kubeConfigEnabled }}
  kubeConfig:
    secretRef:
      name: {{ .kubeConfigSecretName }}
      key: {{ .kubeConfigSecretKey }}
{{- end }}
  chartRef:
    kind: OCIRepository
    name: {{ .prometheusOperatorCRDs.name }}
    namespace: {{ .helmReleaseNamespace }}
  dependsOn: []
  interval: {{ .prometheusOperatorCRDs.interval }}
  releaseName: {{ .prometheusOperatorCRDs.name }}
  targetNamespace: {{ .prometheusOperatorCRDs.targetNamespace }}
  timeout: 15m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 3
{{- if .prometheusOperatorCRDs.values }}
  values:
{{ toYaml .prometheusOperatorCRDs.values | nindent 4 }}
{{- end }}
{{- end }}
