//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdminSecretRef) DeepCopyInto(out *AdminSecretRef) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdminSecretRef.
func (in *AdminSecretRef) DeepCopy() *AdminSecretRef {
	if in == nil {
		return nil
	}
	out := new(AdminSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KCPAPIVersionKindRef) DeepCopyInto(out *KCPAPIVersionKindRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KCPAPIVersionKindRef.
func (in *KCPAPIVersionKindRef) DeepCopy() *KCPAPIVersionKindRef {
	if in == nil {
		return nil
	}
	out := new(KCPAPIVersionKindRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kcp) DeepCopyInto(out *Kcp) {
	*out = *in
	if in.AdminSecretRef != nil {
		in, out := &in.AdminSecretRef, &out.AdminSecretRef
		*out = new(AdminSecretRef)
		**out = **in
	}
	if in.ProviderConnections != nil {
		in, out := &in.ProviderConnections, &out.ProviderConnections
		*out = make([]ProviderConnection, len(*in))
		copy(*out, *in)
	}
	if in.ExtraProviderConnections != nil {
		in, out := &in.ExtraProviderConnections, &out.ExtraProviderConnections
		*out = make([]ProviderConnection, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kcp.
func (in *Kcp) DeepCopy() *Kcp {
	if in == nil {
		return nil
	}
	out := new(Kcp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KcpWorkspace) DeepCopyInto(out *KcpWorkspace) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KcpWorkspace.
func (in *KcpWorkspace) DeepCopy() *KcpWorkspace {
	if in == nil {
		return nil
	}
	out := new(KcpWorkspace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMFP) DeepCopyInto(out *OpenMFP) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMFP.
func (in *OpenMFP) DeepCopy() *OpenMFP {
	if in == nil {
		return nil
	}
	out := new(OpenMFP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMFP) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMFPList) DeepCopyInto(out *OpenMFPList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenMFP, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMFPList.
func (in *OpenMFPList) DeepCopy() *OpenMFPList {
	if in == nil {
		return nil
	}
	out := new(OpenMFPList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenMFPList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMFPSpec) DeepCopyInto(out *OpenMFPSpec) {
	*out = *in
	in.Kcp.DeepCopyInto(&out.Kcp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMFPSpec.
func (in *OpenMFPSpec) DeepCopy() *OpenMFPSpec {
	if in == nil {
		return nil
	}
	out := new(OpenMFPSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenMFPStatus) DeepCopyInto(out *OpenMFPStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.NextReconcileTime.DeepCopyInto(&out.NextReconcileTime)
	if in.KcpWorkspaces != nil {
		in, out := &in.KcpWorkspaces, &out.KcpWorkspaces
		*out = make([]KcpWorkspace, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenMFPStatus.
func (in *OpenMFPStatus) DeepCopy() *OpenMFPStatus {
	if in == nil {
		return nil
	}
	out := new(OpenMFPStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderConnection) DeepCopyInto(out *ProviderConnection) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderConnection.
func (in *ProviderConnection) DeepCopy() *ProviderConnection {
	if in == nil {
		return nil
	}
	out := new(ProviderConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookConfiguration) DeepCopyInto(out *WebhookConfiguration) {
	*out = *in
	out.SecretRef = in.SecretRef
	out.WebhookRef = in.WebhookRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookConfiguration.
func (in *WebhookConfiguration) DeepCopy() *WebhookConfiguration {
	if in == nil {
		return nil
	}
	out := new(WebhookConfiguration)
	in.DeepCopyInto(out)
	return out
}
