//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentConfig) DeepCopyInto(out *ComponentConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentConfig.
func (in *ComponentConfig) DeepCopy() *ComponentConfig {
	if in == nil {
		return nil
	}
	out := new(ComponentConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultAPIBindingConfiguration) DeepCopyInto(out *DefaultAPIBindingConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultAPIBindingConfiguration.
func (in *DefaultAPIBindingConfiguration) DeepCopy() *DefaultAPIBindingConfiguration {
	if in == nil {
		return nil
	}
	out := new(DefaultAPIBindingConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExposureConfig) DeepCopyInto(out *ExposureConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExposureConfig.
func (in *ExposureConfig) DeepCopy() *ExposureConfig {
	if in == nil {
		return nil
	}
	out := new(ExposureConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitializerConnection) DeepCopyInto(out *InitializerConnection) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitializerConnection.
func (in *InitializerConnection) DeepCopy() *InitializerConnection {
	if in == nil {
		return nil
	}
	out := new(InitializerConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KCPAPIVersionKindRef) DeepCopyInto(out *KCPAPIVersionKindRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KCPAPIVersionKindRef.
func (in *KCPAPIVersionKindRef) DeepCopy() *KCPAPIVersionKindRef {
	if in == nil {
		return nil
	}
	out := new(KCPAPIVersionKindRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kcp) DeepCopyInto(out *Kcp) {
	*out = *in
	if in.ProviderConnections != nil {
		in, out := &in.ProviderConnections, &out.ProviderConnections
		*out = make([]ProviderConnection, len(*in))
		copy(*out, *in)
	}
	if in.ExtraProviderConnections != nil {
		in, out := &in.ExtraProviderConnections, &out.ExtraProviderConnections
		*out = make([]ProviderConnection, len(*in))
		copy(*out, *in)
	}
	if in.InitializerConnections != nil {
		in, out := &in.InitializerConnections, &out.InitializerConnections
		*out = make([]InitializerConnection, len(*in))
		copy(*out, *in)
	}
	if in.ExtraInitializerConnections != nil {
		in, out := &in.ExtraInitializerConnections, &out.ExtraInitializerConnections
		*out = make([]InitializerConnection, len(*in))
		copy(*out, *in)
	}
	if in.ExtraDefaultAPIBindings != nil {
		in, out := &in.ExtraDefaultAPIBindings, &out.ExtraDefaultAPIBindings
		*out = make([]DefaultAPIBindingConfiguration, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kcp.
func (in *Kcp) DeepCopy() *Kcp {
	if in == nil {
		return nil
	}
	out := new(Kcp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KcpWorkspace) DeepCopyInto(out *KcpWorkspace) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KcpWorkspace.
func (in *KcpWorkspace) DeepCopy() *KcpWorkspace {
	if in == nil {
		return nil
	}
	out := new(KcpWorkspace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCMConfig) DeepCopyInto(out *OCMConfig) {
	*out = *in
	out.Repo = in.Repo
	out.Component = in.Component
	if in.ReferencePath != nil {
		in, out := &in.ReferencePath, &out.ReferencePath
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCMConfig.
func (in *OCMConfig) DeepCopy() *OCMConfig {
	if in == nil {
		return nil
	}
	out := new(OCMConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformMesh) DeepCopyInto(out *PlatformMesh) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformMesh.
func (in *PlatformMesh) DeepCopy() *PlatformMesh {
	if in == nil {
		return nil
	}
	out := new(PlatformMesh)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlatformMesh) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformMeshList) DeepCopyInto(out *PlatformMeshList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PlatformMesh, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformMeshList.
func (in *PlatformMeshList) DeepCopy() *PlatformMeshList {
	if in == nil {
		return nil
	}
	out := new(PlatformMeshList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PlatformMeshList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformMeshSpec) DeepCopyInto(out *PlatformMeshSpec) {
	*out = *in
	if in.Exposure != nil {
		in, out := &in.Exposure, &out.Exposure
		*out = new(ExposureConfig)
		**out = **in
	}
	in.Kcp.DeepCopyInto(&out.Kcp)
	in.Values.DeepCopyInto(&out.Values)
	if in.OCM != nil {
		in, out := &in.OCM, &out.OCM
		*out = new(OCMConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformMeshSpec.
func (in *PlatformMeshSpec) DeepCopy() *PlatformMeshSpec {
	if in == nil {
		return nil
	}
	out := new(PlatformMeshSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformMeshStatus) DeepCopyInto(out *PlatformMeshStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.NextReconcileTime.DeepCopyInto(&out.NextReconcileTime)
	if in.KcpWorkspaces != nil {
		in, out := &in.KcpWorkspaces, &out.KcpWorkspaces
		*out = make([]KcpWorkspace, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformMeshStatus.
func (in *PlatformMeshStatus) DeepCopy() *PlatformMeshStatus {
	if in == nil {
		return nil
	}
	out := new(PlatformMeshStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderConnection) DeepCopyInto(out *ProviderConnection) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderConnection.
func (in *ProviderConnection) DeepCopy() *ProviderConnection {
	if in == nil {
		return nil
	}
	out := new(ProviderConnection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RepoConfig) DeepCopyInto(out *RepoConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RepoConfig.
func (in *RepoConfig) DeepCopy() *RepoConfig {
	if in == nil {
		return nil
	}
	out := new(RepoConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookConfiguration) DeepCopyInto(out *WebhookConfiguration) {
	*out = *in
	out.SecretRef = in.SecretRef
	out.WebhookRef = in.WebhookRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookConfiguration.
func (in *WebhookConfiguration) DeepCopy() *WebhookConfiguration {
	if in == nil {
		return nil
	}
	out := new(WebhookConfiguration)
	in.DeepCopyInto(out)
	return out
}
