apiVersion: apis.kcp.io/v1alpha1
kind: APIExport
metadata:
  creationTimestamp: null
  name: core.platform-mesh.io
spec:
  latestResourceSchemas:
  - v250715-5b899f6.accountinfos.core.platform-mesh.io
  - v250715-5b899f6.accounts.core.platform-mesh.io
  permissionClaims:
    - all: true
      group: tenancy.kcp.io
      identityHash: {{ .apiExportRootTenancyKcpIoIdentityHash }}
      resource: workspaces
    - all: true
      group: tenancy.kcp.io
      identityHash: {{ .apiExportRootTenancyKcpIoIdentityHash }}
      resource: workspacetypes
status: {}
