apiVersion: apis.kcp.io/v1alpha1
kind: APIResourceSchema
metadata:
  creationTimestamp: null
  name: v250715-52c3ed0.providermetadatas.core.openmfp.io
spec:
  group: core.openmfp.io
  names:
    kind: ProviderMetadata
    listKind: ProviderMetadataList
    plural: providermetadatas
    singular: providermetadata
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      description: ProviderMetadata is the Schema for the providermetadata API.
      properties:
        apiVersion:
          description: |-
            APIVersion defines the versioned schema of this representation of an object.
            Servers should convert recognized schemas to the latest internal value, and
            may reject unrecognized values.
            More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
          type: string
        kind:
          description: |-
            Kind is a string value representing the REST resource this object represents.
            Servers may infer this from the endpoint the client submits requests to.
            Cannot be updated.
            In CamelCase.
            More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
          type: string
        metadata:
          type: object
        spec:
          description: ProviderMetadataSpec defines the desired state of ProviderMetadata.
          properties:
            contacts:
              items:
                properties:
                  displayName:
                    type: string
                  email:
                    type: string
                  role:
                    items:
                      type: string
                    type: array
                required:
                - displayName
                type: object
              type: array
            data:
              description: Additional information that should be stored with the provider
                metadata.
              x-kubernetes-preserve-unknown-fields: true
            description:
              type: string
            displayName:
              type: string
            documentation:
              properties:
                url:
                  type: string
              type: object
            helpCenterData:
              items:
                properties:
                  URL:
                    type: string
                  displayName:
                    type: string
                type: object
              type: array
            icon:
              properties:
                dark:
                  properties:
                    data:
                      type: string
                    url:
                      type: string
                  type: object
                light:
                  properties:
                    data:
                      type: string
                    url:
                      type: string
                  type: object
              required:
              - dark
              - light
              type: object
            links:
              items:
                properties:
                  URL:
                    type: string
                  displayName:
                    type: string
                type: object
              type: array
            preferredSupportChannels:
              items:
                properties:
                  URL:
                    type: string
                  displayName:
                    type: string
                type: object
              type: array
            tags:
              items:
                type: string
              type: array
          required:
          - displayName
          type: object
        status:
          description: ProviderMetadataStatus defines the observed state of ProviderMetadata.
          type: object
      type: object
    served: true
    storage: true
    subresources:
      status: {}
