apiVersion: core.openmfp.io/v1alpha1
kind: ContentConfiguration
metadata:
  labels:
    portal.openmfp.org/entity: main
  name: main-iam-ui
spec:
  inlineConfiguration:
    content: |-
      {
        "name": "iam-ui",
        "luigiConfigFragment": {
          "data": {
            "nodes": [
              {
                "pathSegment": "members",
                "label": "Members",
                "icon": "company-view",
                "entityType": "main",
                "url": "https://{{ .baseDomain }}/ui/iam/#/organization/members",
                "context": {
                  "entityType": "account",
                  "entityContext": {
                    "account": {
                      "policies": ["iamAdmin", "projectAdmin", "projectMember"]
                    }
                  }
                }
              },
              {
                "pathSegment": "add-members",
                "entityType": "main",
                "label": "Members",
                "hideFromNav": true,
                "url": "https://{{ .baseDomain }}/ui/iam/#/organization/add-members",
                "context": {
                  "entityType": "account"
                }
              }
            ],
            "texts": [ ]
          }
        }
      }
    contentType: json
