apiVersion: delivery.ocm.software/v1alpha1
kind: FluxDeployer
metadata:
  name: istio-base
  namespace: default
spec:
  interval: 10m0s
  sourceRef:
    apiVersion: delivery.ocm.software/v1alpha1
    kind: Resource
    name: istio-base
  helmReleaseTemplate:
    interval: 10s
    releaseName: istio-base
    targetNamespace: istio-system
    install:
      createNamespace: true
    driftDetection:
      mode: disabled
      ignore:
        - paths: [ "/spec/replicas" ]
        - paths: [ "/data" ]
