apiVersion: delivery.ocm.software/v1alpha1
kind: FluxDeployer
metadata:
  name: fga-operator
  namespace: default
spec:
  interval: 10m0s
  sourceRef:
    apiVersion: delivery.ocm.software/v1alpha1
    kind: Resource
    name: fga-operator
  helmReleaseTemplate:
    interval: 10s
    releaseName: fga-operator
    targetNamespace: openmfp-system
    dependsOn:
      - name: kcp
        namespace: default
    driftDetection:
      mode: enabled
      ignore:
        - paths: [ "/spec/replicas" ]
        - paths: [ "/data" ]
    values:
      fga:
        target: openfga.openmfp-system.svc.cluster.local:8081
      initializer:
        kubeconfigSecret: fga-initializer-kubeconfig
      kubeconfigSecret: fga-operator-kubeconfig
      log:
        level: debug
      operator:
        shutdownTimeout: 1m
        maxConcurrentReconciles: 1
