{{- if .gatewayApi.enabled }}
apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  labels:
    artifact: chart
    repo: git
  name: {{ .gatewayApi.name }}
  namespace: {{ .helmReleaseNamespace }}
spec:
  componentRef:
    name: {{ .ocm.component.name }}
  interval: {{ .ocm.interval }}
  ocmConfig:
    - apiVersion: delivery.ocm.software/v1alpha1
      kind: Repository
      name: {{ .ocm.repo.name }}
      namespace: {{ .releaseNamespace }}
  resource:
    byReference:
      referencePath:
      {{- range .ocm.referencePath }}
        - name: {{ .name }}
      {{- end }}
        - name: {{ .gatewayApi.name }}
      resource:
        name: {{ .gatewayApi.ocmResourceName }}
  skipVerify: {{ .ocm.skipVerify }}
{{- end }}