apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: security-initializer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: security-initializer
subjects:
- kind: ServiceAccount
  name: platform-mesh-provider-security-initializer-kubeconfig
  namespace: default
