apiVersion: delivery.ocm.software/v1alpha1
kind: FluxDeployer
metadata:
  name: iam-authorization-webhook
  namespace: default
spec:
  interval: 10m0s
  sourceRef:
    apiVersion: delivery.ocm.software/v1alpha1
    kind: Resource
    name: iam-authorization-webhook
  helmReleaseTemplate:
    interval: 10s
    releaseName: iam-authorization-webhook
    targetNamespace: openmfp-system
    dependsOn:
      - name: istio-istiod
        namespace: default
    driftDetection:
      mode: enabled
      ignore:
        - paths: [ "/spec/replicas" ]
        - paths: [ "/data" ]
    values:
      log:
        level: debug
      openfga:
        url: openfga:8081
        storeName: ""
      istio:
        exposed: false
        dnsNames:
          - iam-authorization-webhook.openmfp-system.svc.cluster.local
      certManager:
        enabled: true
        createCA: true
      extraVolumeMounts:
        - name: rules-config
          mountPath: /var/data/rules
        - name: kcp-kubeconfig
          mountPath: /etc/kcp-kubeconfig
          readOnly: true
      extraVolumes:
        - name: rules-config
          configMap:
            name: iam-authorization-webhook-rules
        - name: kcp-kubeconfig
          secret:
            secretName: iam-authorization-webhook-kubeconfig
      extraEnvs:
        - name: KCP_ENABLED
          value: "true"
        - name: KCP_KUBECONFIGPATH
          value: "/etc/kcp-kubeconfig/kubeconfig"
        - name: KCP_CLUSTERURL
          value: https://kcp:6443/
      rules: |
        rules:
          - apiGroup: core.openmfp.org
            resource: accounts
            object: account
            verb: list
            relation: list
            reference: kcp
          - apiGroup: core.openmfp.org
            resource: accounts
            object: account
            verb: get
            relation: get
            reference: kcp
          - apiGroup: core.openmfp.org
            resource: accounts
            object: account
            verb: watch
            relation: watch
            reference: kcp
          - apiGroup: core.openmfp.org
            resource: accounts
            object: account
            verb: create
            relation: create
            reference: kcp
          - apiGroup: ""
            resource: namespaces
            verb: create
            relation: create_v1_namespace
            object: account
            reference: kcp
          - apiGroup: ""
            resource: namespaces
            verb: list
            relation: list_v1_namespace
            object: account
            reference: kcp
          - apiGroup: ""
            resource: namespaces
            verb: watch
            relation: watch_v1_namespace
            object: account
            reference: kcp
