apiVersion: delivery.ocm.software/v1alpha1
kind: FluxDeployer
metadata:
  name: apeiro-portal
  namespace: default
spec:
  interval: 10m0s
  sourceRef:
    apiVersion: delivery.ocm.software/v1alpha1
    kind: Resource
    name: apeiro-portal
  helmReleaseTemplate:
    interval: 10s
    releaseName: apeiro-portal
    targetNamespace: openmfp-system
    dependsOn:
      - name: keycloak
        namespace: default
    driftDetection:
      mode: enabled
      ignore:
        - paths: [ "/spec/replicas" ]
        - paths: [ "/data" ]
    values:
      crdGatewayApiUrl: "https://${org-subdomain}portal.{{ .BASE_DOMAIN }}/api/kubernetes-graphql-gateway/root:orgs:${org-name}/graphql"
      environment: kind
      http:
        protocol: https
      frontendPort: 8443
      trust:
        openmfp:
          # -- base domains
          baseDomains: "{{ .BASE_DOMAIN }}"
          # -- discovery endpoint. If specified (different than ""), authDomain and tokenUrl are not required
          discoveryEndpoint: ""
          # -- auth domain (if discoveryEndpoint is not specified)
          authDomain: https://portal.{{ .BASE_DOMAIN }}{{ .COLON_PORT }}/keycloak/realms/openmfp/protocol/openid-connect/auth
          # -- token url (if discoveryEndpoint is not specified)
          tokenUrl: http://openmfp-keycloak/keycloak/realms/openmfp/protocol/openid-connect/token
          # -- oidc client secret name
          oidcClientSecretName: openmfp-client
          # -- login audience
          loginAudience: openmfp
          # -- secret key reference
          secretKeyRef: attribute.client_secret
          # -- ContentConfiguration validator api url
          contentConfigurationValidatorApiUrl: http://openmfp-extension-manager-operator-server.openmfp-system.svc.cluster.local:8088/validate
      virtualService:
        hosts: false
      baseDomains:
        - {{ .BASE_DOMAIN }}
      cookieDomain: {{ .BASE_DOMAIN }}
      extraEnvVars:
        - name: KUBERNETES_GRAPHQL_GATEWAY_API_URL
          value: https://portal.dev.local:8443/api/kubernetes-graphql-gateway/root:orgs:openmfp/graphql
