apiVersion: tenancy.kcp.io/v1alpha1
kind: WorkspaceType
metadata:
  name: account
spec:
  defaultAPIBindings:
    - export: openmfp.org
      path: root:openmfp-system
    - export: tenancy.kcp.io
      path: root
    - export: topology.kcp.io
      path: root
  defaultChildWorkspaceType:
    name: account
    path: root
  limitAllowedChildren:
    types:
      - name: account
        path: root
  limitAllowedParents:
    types:
      - name: org
        path: root
      - name: account
        path: root