//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluxComponentSpec) DeepCopyInto(out *FluxComponentSpec) {
	*out = *in
	in.Values.DeepCopyInto(&out.Values)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluxComponentSpec.
func (in *FluxComponentSpec) DeepCopy() *FluxComponentSpec {
	if in == nil {
		return nil
	}
	out := new(FluxComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeconfigSecretSpec) DeepCopyInto(out *KubeconfigSecretSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeconfigSecretSpec.
func (in *KubeconfigSecretSpec) DeepCopy() *KubeconfigSecretSpec {
	if in == nil {
		return nil
	}
	out := new(KubeconfigSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalKubeconfigSecretSpec) DeepCopyInto(out *LocalKubeconfigSecretSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalKubeconfigSecretSpec.
func (in *LocalKubeconfigSecretSpec) DeepCopy() *LocalKubeconfigSecretSpec {
	if in == nil {
		return nil
	}
	out := new(LocalKubeconfigSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedProvider) DeepCopyInto(out *ManagedProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedProvider.
func (in *ManagedProvider) DeepCopy() *ManagedProvider {
	if in == nil {
		return nil
	}
	out := new(ManagedProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedProviderList) DeepCopyInto(out *ManagedProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManagedProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedProviderList.
func (in *ManagedProviderList) DeepCopy() *ManagedProviderList {
	if in == nil {
		return nil
	}
	out := new(ManagedProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedProviderSpec) DeepCopyInto(out *ManagedProviderSpec) {
	*out = *in
	if in.ProviderReference != nil {
		in, out := &in.ProviderReference, &out.ProviderReference
		*out = new(ProviderReferenceSpec)
		**out = **in
	}
	if in.ProviderKubeconfigSecret != nil {
		in, out := &in.ProviderKubeconfigSecret, &out.ProviderKubeconfigSecret
		*out = new(LocalKubeconfigSecretSpec)
		**out = **in
	}
	out.PlatformMeshReference = in.PlatformMeshReference
	if in.RuntimeDeployments != nil {
		in, out := &in.RuntimeDeployments, &out.RuntimeDeployments
		*out = make([]ProviderComponentSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedProviderSpec.
func (in *ManagedProviderSpec) DeepCopy() *ManagedProviderSpec {
	if in == nil {
		return nil
	}
	out := new(ManagedProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedProviderStatus) DeepCopyInto(out *ManagedProviderStatus) {
	*out = *in
	if in.ProviderKubeconfigSecretRef != nil {
		in, out := &in.ProviderKubeconfigSecretRef, &out.ProviderKubeconfigSecretRef
		*out = new(v1.SecretReference)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedProviderStatus.
func (in *ManagedProviderStatus) DeepCopy() *ManagedProviderStatus {
	if in == nil {
		return nil
	}
	out := new(ManagedProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCMComponentSpec) DeepCopyInto(out *OCMComponentSpec) {
	*out = *in
	if in.ReferencePath != nil {
		in, out := &in.ReferencePath, &out.ReferencePath
		*out = make([]OCMReferencePathElement, len(*in))
		copy(*out, *in)
	}
	in.Values.DeepCopyInto(&out.Values)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCMComponentSpec.
func (in *OCMComponentSpec) DeepCopy() *OCMComponentSpec {
	if in == nil {
		return nil
	}
	out := new(OCMComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OCMReferencePathElement) DeepCopyInto(out *OCMReferencePathElement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OCMReferencePathElement.
func (in *OCMReferencePathElement) DeepCopy() *OCMReferencePathElement {
	if in == nil {
		return nil
	}
	out := new(OCMReferencePathElement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PlatformMeshReferenceSpec) DeepCopyInto(out *PlatformMeshReferenceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PlatformMeshReferenceSpec.
func (in *PlatformMeshReferenceSpec) DeepCopy() *PlatformMeshReferenceSpec {
	if in == nil {
		return nil
	}
	out := new(PlatformMeshReferenceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Provider) DeepCopyInto(out *Provider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Provider.
func (in *Provider) DeepCopy() *Provider {
	if in == nil {
		return nil
	}
	out := new(Provider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Provider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderComponentSpec) DeepCopyInto(out *ProviderComponentSpec) {
	*out = *in
	if in.Flux != nil {
		in, out := &in.Flux, &out.Flux
		*out = new(FluxComponentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.OCM != nil {
		in, out := &in.OCM, &out.OCM
		*out = new(OCMComponentSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderComponentSpec.
func (in *ProviderComponentSpec) DeepCopy() *ProviderComponentSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderList) DeepCopyInto(out *ProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Provider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderList.
func (in *ProviderList) DeepCopy() *ProviderList {
	if in == nil {
		return nil
	}
	out := new(ProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderReferenceSpec) DeepCopyInto(out *ProviderReferenceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderReferenceSpec.
func (in *ProviderReferenceSpec) DeepCopy() *ProviderReferenceSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderReferenceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderSpec) DeepCopyInto(out *ProviderSpec) {
	*out = *in
	if in.ProviderKubeconfigSecret != nil {
		in, out := &in.ProviderKubeconfigSecret, &out.ProviderKubeconfigSecret
		*out = new(KubeconfigSecretSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderSpec.
func (in *ProviderSpec) DeepCopy() *ProviderSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderStatus) DeepCopyInto(out *ProviderStatus) {
	*out = *in
	if in.ProviderKubeconfigSecretRef != nil {
		in, out := &in.ProviderKubeconfigSecretRef, &out.ProviderKubeconfigSecretRef
		*out = new(v1.SecretReference)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderStatus.
func (in *ProviderStatus) DeepCopy() *ProviderStatus {
	if in == nil {
		return nil
	}
	out := new(ProviderStatus)
	in.DeepCopyInto(out)
	return out
}
