{{- if .certManager.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ .certManager.name }}
  namespace: {{ .helmReleaseNamespace }}
  labels:
    core.platform-mesh.io/operator-created: "true"
spec:
{{- if .kubeConfigEnabled }}
  kubeConfig:
    secretRef:
      name: {{ .kubeConfigSecretName }}
      key: {{ .kubeConfigSecretKey }}
{{- end }}
  chartRef:
    kind: OCIRepository
    name: {{ .certManager.name }}
    namespace: {{ .helmReleaseNamespace }}
  interval: {{ .certManager.interval }}
  releaseName: {{ .certManager.name }}
  targetNamespace: {{ .certManager.targetNamespace }}
  timeout: 15m
  values:
{{ toYaml .certManager.values | nindent 4 }}
{{- end }}