# .github/workflows/labeler.yml
name: Pull Request Labeler

on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]

jobs:
  auto-labeler:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    if: ${{ (github.head_ref || github.ref) != format('refs/heads/{0}',inputs.release_branch) }}
    uses: platform-mesh/.github/.github/workflows/job-auto-labeler.yml@fix/auto-labeler-perm
    secrets: inherit
